### PR TITLE
Add a memory safe LeptonicaVersion struct wrapper

### PR DESCRIPTION
**Pull request by kvnxiao**
Update to https://github.com/ccouzens/leptonica-plumbing/pull/3

### CODE REVIEW

**Comment by ccouzens** [comment]
Hey, thank you for this PR.

Add thank you houqp for responding to the last one in my absence 🙂.

I think we could have a `LeptonicaString` type (or `leptonica_plumbing::String`) that is returned by `get_version` and `get_imagelib_versions`. Probably it will be returned by other leptonica methods too.

This new string type could implement `Drop` by `free`ing its memory. And it could implement

```rust
impl AsRef<CStr> for LeptonicaString {
    fn as_ref(&self) -> &CStr {
        unsafe { CStr::from_ptr(self.0) }
    }
}
```

By having a specific type for string:
* It's reusable for other leptonica methods that return heap memory
* and it doesn't require someone who wants to just use one of the 2 version methods to call both.

**Comment by kvnxiao** [comment]
Would it be better to implement `AsRef<str>` over `AsRef<CStr>`?

And should we also implement Deref like std `String` for &str?

e.g.

```rust
impl Deref for LeptonicaString {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.as_ref()  // via impl AsRef<str>
    }
}
```

**Comment by ccouzens** [comment]
> Would it be better to implement `AsRef<str>` over `AsRef<CStr>`?


Why not both?

Because of the type parameter you can have a

```rust
impl AsRef<CStr> for LeptonicaString {
```

block and a

```rust
impl AsRef<str> for LeptonicaString {
```

block.

but then depending on context you may need to be a little more specific as there are 2 `as_ref`s.

```
let a: str = s.as_ref();
let b = s.as_ref::<CStr>();
```

> 
> And should we also implement Deref like std `String` for &str?
> 
> e.g.
> 
> ```rust
> impl Deref for LeptonicaString {
>     type Target = str;
> 
>     fn deref(&self) -> &Self::Target {
>         &self.as_ref()  // via impl AsRef<str>
>     }
> }
> ```

I don't think that would be a great idea.

To get to a `str` you will probably use `unwrap` (because of https://doc.rust-lang.org/core/ffi/struct.CStr.html#method.to_str).

The [documentation](https://doc.rust-lang.org/std/ops/trait.Deref.html) for `Deref` says

> this trait should never fail

I think it's fair to assume that leptonica will only ever return ASCII or UTF-8. But in the event that it ever returns invalid UTF-8 then we don't want `Deref` to behave in a confusing manner.

**Comment by kvnxiao** [comment]
@ccouzens made the changes accordingly, please take a look.

**Review by ccouzens — APPROVED** [review]

**Comment by ccouzens** [comment]
> @ccouzens made the changes accordingly, please take a look.

Looks good. Thank you.

I'll get it merged and released. And `tesseract-plumbing` updated to reference this new version.

**Pull request merged**
